
SELECT CURDATE()-3 AS REGDATE ,a.DSC_DR, c.FNAME, count(a.DSC_DR) AS AMOUNT
FROM ipd_reg a
INNER JOIN staff b ON a.DSC_DR = b.STAFF_ID
LEFT JOIN population c ON b.CID = c.CID
WHERE a.DSC_DT > CURDATE()-3
AND a.DSC_DR <> ' '
GROUP BY a.DSC_DR ORDER BY AMOUNT DESC