SELECT  CURDATE() AS REGDATE,
CASE
WHEN a.WARD_NO = 38 THEN 'WARD2'
WHEN a.WARD_NO = 39 THEN 'WARD1'
END WARD_NO , COUNT(CASE WHEN (a.ADM_DT > CURDATE()) THEN '1' END) AS 'ADMIT', 
COUNT(CASE WHEN (a.DSC_DT > CURDATE()) THEN '2' END) AS 'DISCHARGE'
FROM ipd_reg a
WHERE a.IS_CANCEL = 0
AND (a.ADM_DT > CURDATE() OR a.DSC_DT > CURDATE())
GROUP BY a.WARD_NO



