SELECT P_DIAG ,COUNT(P_DIAG) AS amount
FROM ipd_reg
WHERE DSC_DT >'20151001'
AND IS_CANCEL = 0
AND NOT  LEFT(P_DIAG,2)= '[O'
AND NOT LEFT(P_DIAG,2) = '[z'
GROUP BY P_DIAG ORDER BY amount DESC  LIMIT 20;