SELECT a.VISIT_ID,a.ADM_DT,a.DSC_DT,a.ADM_ID,e.HN,ICD10_TM,ICD_NAME
FROM ipd_reg a,opd_diagnosis b,icd10new c ,opd_visits e
WHERE a.DSC_DT > '20151001'
AND a.VISIT_ID = b.VISIT_ID
AND a.IS_CANCEL = 0
AND b.ICD10 = c.ICD10
AND c.ICD10_TM NOT BETWEEN 'z00'AND 'z99'
AND c.ICD10_TM NOT BETWEEN 'o00'AND 'o99'
AND b.DXT_ID = 1
AND a.VISIT_ID = e.VISIT_ID
GROUP BY a.VISIT_ID,a.ADM_ID ;


