SELECT DISTINCT a.CID,c.FNAME , c.LNAME , c.SEX ,c.BIRTHDATE,FLOOR(DATEDIFF(NOW(),c.BIRTHDATE)/365.25)AS AGE,
c.HOME_ADR,c.TOWN_ID, b.DRUG_NAME,a.UPD_DT AS ALLERGY_DATE,a.LEVEL,a.ALLERGY_NOTE
FROM cid_drug_allergy a, drugs b, population c
WHERE a.DRUG_ID = b.DRUG_ID
AND a.IS_CANCEL = 0
AND a.CID = c.CID
 
