SELECT'10953'AS 'HOSPCODE', NDC24 , CONCAT(GENERICNAME , ' ' ,strength) AS 'DNAME',
CASE
	WHEN ISED_APPROVED = 'E' THEN 'ED'
	WHEN ISED_APPROVED = 'E*'THEN 'ED'
	WHEN ISED_APPROVED = 'N' then 'NonED'
END AS 'NLEM'
FROM drug_catalogue 
WHERE   NDC24 != ' '
GROUP BY NDC24



