SELECT f.REG_DATETIME AS REGDATE,f.HN, b.ADM_ID AS AN ,b.ADM_DT,a.RF_DT ,d.ICD_NAME AS DIAG_LAST ,e.UNIT_NAME 
FROM refers a, hosp_nhso g, opd_diagnosis c, icd10new d, service_units e, ipd_reg b
LEFT JOIN opd_visits f ON f.VISIT_ID = b.VISIT_ID
WHERE  a.RF_DT >'20100101'
AND a.IS_CANCEL = 0
AND a.RF_TYPE = 2
AND a.VISIT_ID = b.VISIT_ID 
AND b.IS_CANCEL = 0
AND b.VISIT_ID = c.VISIT_ID
AND c.ICD10 = d.ICD10
AND b.WARD_NO = e.UNIT_ID
AND c.DXT_ID = 1
AND a.HOSP_ID = g.HOSP_ID
GROUP BY a.VISIT_ID


SELECT  UNIT_NAME,  COUNT(UNIT_NAME) AS AMOUNT
FROM  mb_refer_ipd
WHERE RF_DT BETWEEN '20151001' AND '20151030'
GROUP BY UNIT_NAME WITH ROLLUP  ;





