
SELECT a.HN, a.REGDATE, a.FNAME,a.LNAME,a.SEX,a.AGE, a.ICD10_TM, a.UNIT_NAME,a.HOME_ADR,
b.TOWN_NAME AS 'MOOBAN', c.TOWN_NAME AS 'TUMBOL', d.TOWN_NAME AS 'AUMPUR', e.TOWN_NAME AS 'JUNGWAT'
FROM mb_dxopd a, towns b, towns c, towns d,towns e
WHERE a.REGDATE BETWEEN '2016-10-01' AND '2017-09-30'
AND LOCATE('E1',a.ICD10_TM)>0
AND a.UNIT_REG = '15'
AND a.TOWN_ID = b.TOWN_ID
AND CONCAT(LEFT(a.TOWN_ID,6),'00')= c.TOWN_ID
AND CONCAT(LEFT(a.TOWN_ID,4),'0000') = d.TOWN_ID
AND CONCAT(LEFT(a.TOWN_ID,2),'000000') = e.TOWN_ID
GROUP BY a.HN ORDER BY REGDATE ; 
