SELECT a.VISIT_ID, a.HN, DATE_FORMAT(a.REG_DATETIME,'%Y-%m-%d') AS 'REGDATE',e.FNAME, e.LNAME,
e.SEX, FLOOR(DATEDIFF(NOW(),e.BIRTHDATE) /365.25) AS 'AGE' ,a.UNIT_REG,f.UNIT_NAME,
a.STAFF_ID,a.INSCL,c.ICD10_TM,c.ICD_NAME,e.TOWN_ID
FROM opd_visits a,opd_diagnosis b,icd10new c, cid_hn d , population e, service_units f
WHERE a.REG_DATETIME >'20170301'
AND a.VISIT_ID = b.VISIT_ID
AND a.IS_CANCEL = 0
AND b.DXG_ID = 1
AND b.ICD10 = c.ICD10
AND a.VISIT_ID NOT IN (SELECT VISIT_ID FROM ipd_reg)
AND a.HN = d.HN 
AND d.CID = e.CID
AND a.UNIT_REG = f.UNIT_ID
GROUP BY a.VISIT_ID