SELECT a.VISIT_ID,b.HN, a.ADM_ID, DATE_FORMAT(a.ADM_DT,'%Y-%m-%d') AS D_ADMITT, DATE_FORMAT(a.DSC_DT,'%Y-%m-%d') AS D_DSC,
a.DSC_TYPE, a.DSC_STATUS, a.WARD_NO, a.DSC_DR, a.ADM_DR, a.P_DIAG, a.ADJRW,a.RW
FROM ipd_reg a
LEFT JOIN opd_visits b ON a.VISIT_ID = b.VISIT_ID AND b.IS_CANCEL = 0
WHERE a.ADM_DT BETWEEN '20170101' AND '20170131'
AND a.IS_CANCEL = 0
AND a.WARD_NO = 22
GROUP BY a.VISIT_ID ORDER BY a.VISIT_ID,D_ADMITT ;
