SELECT a.CID, a.FNAME, a.LNAME, a.SEX, a.AGE, a.BIRTHDATE,a.HOME_ADR, b.TOWN_NAME AS 'MOOBAN' , c.TOWN_NAME AS 'TUMBOL', d.TOWN_NAME AS 'AUMPUR',
a.DRUG_NAME, a.ALLERGY_DATE , a.`LEVEL`, a.ALLERGY_NOTE
FROM mb_drug_allergy a, towns b, towns c ,towns d
WHERE a.TOWN_ID = b.TOWN_ID
AND CONCAT(left(a.TOWN_ID,6),'00') = c.TOWN_ID
AND CONCAT(left(a.TOWN_ID,4),'0000') = d.TOWN_ID
ORDER BY ALLERGY_DATE ; 
 