SELECT DISTINCT a.HN,c.FNAME, c.LNAME ,FLOOR(DATEDIFF(NOW(),c.BIRTHDATE)/365.25) AS AGE,
c.SEX,c.BIRTHDATE,d.UNIT_NAME,d.UNIT_ID
FROM opd_visits a, cid_hn b, population c,service_units d
WHERE a.REG_DATETIME > '201601001' AND '20170430'
AND a.IS_CANCEL = 0
AND a.HN = b.HN
AND b.CID = c.CID 
AND a.UNIT_REG = '12'
AND a.UNIT_REG = d.UNIT_ID;
GROUP BY a.HN ORDER BY a.HN ; 
