SELECT a.REGDATE , a.HN , a.FNAME , a.LNAME ,a.SEX, a.AGE ,a.UNIT_NAME,a.ICD10_TM,
 a.HOME_ADR, b.TOWN_NAME AS 'MOOBAN' , c.TOWN_NAME AS 'TUMBOL' , d.TOWN_NAME AS 'AUMPUR'
FROM mb_dxopd a, towns b, towns c, towns d
WHERE REGDATE BETWEEN '2015-10-01' AND '2016-09-30'
AND a.UNIT_REG IN ('03','04','05')
AND a.AGE >= 60
AND a.TOWN_ID = b.TOWN_ID
AND CONCAT(left(a.TOWN_ID,6),'00') = c.TOWN_ID
AND CONCAT(left(a.TOWN_ID,4),'0000') = d.TOWN_ID
GROUP BY a.HN ORDER BY a.REGDATE,a.HN ;
 