SELECT DISTINCT YEAR(k.BDATE) AS 
FROM (
SELECT a.CID_BABY, c.HN , a.FNAME ,a.LNAME, a.CID_MOM, a.SEX,a.BDATE,a.BWEIGHT,b.GA, b.GRAVIDA
FROM anc_outcome a, anc b, cid_hn c
WHERE a.BDATE >'20140101'
AND a.ANC_NO = b.ANC_NO
AND a.CID_BABY = c.CID
AND a.IS_CANCEL = 0
GROUP BY a.CID_BABY) AS k  ;
