SELECT
	a.HN,
	a.REGDATE,
	a.FNAME,
	a.LNAME,
	a.SEX,
	a.AGE,
	a.ICD10_TM,
	a.UNIT_NAME,
  a.TOWN_ID,
	a.HOME_ADR,
	b.TOWN_NAME AS 'MOOBAN',
	c.TOWN_NAME AS 'TUMBOL',
	d.TOWN_NAME AS 'AUMPUR',
	e.TOWN_NAME AS 'JUNGWAT'
FROM
	mb_dxopd a,
	towns b,
	towns c,
	towns d,
	towns e
WHERE
	a.REGDATE  > '2016-10-01'
AND a.UNIT_REG = '12'
AND a.ICD10_TM BETWEEN 'J45' AND 'J46'
AND a.TOWN_ID = b.TOWN_ID
AND CONCAT(LEFT(a.TOWN_ID, 6), '00') = c.TOWN_ID
AND CONCAT(LEFT(a.TOWN_ID, 4), '0000') = d.TOWN_ID
AND CONCAT(LEFT(a.TOWN_ID, 2), '000000') = e.TOWN_ID
GROUP BY
	a.HN
ORDER BY
	REGDATE  ;