SELECT DISTINCT CONCAT(a.VISIT_ID,'',RIGHT(c.ICD9,5)) AS ID, a.REG_DATETIME , a.VISIT_ID, a.HN ,c.CODE,c.NICKNAME,
 a.INSCL,b.SURGEON_ID, b.STAFF_ID, c.CGD_ID
FROM opd_visits a
INNER JOIN opd_operations b ON a.VISIT_ID = b.VISIT_ID AND b.is_cancel = 0
INNER JOIN  icd9cm c ON b.icd9 = c.icd9 
# AND c.NICKNAME BETWEEN 'PT00' AND 'PT75'
WHERE a.REG_DATETIME BETWEEN '2018.06.01' AND '2018.06.31'
AND a.is_cancel = 0