SELECT a.INSCL, b.INSCL_NAME, COUNT(a.INSCL) AS AMOUNT
FROM mb_opd_operations a
INNER JOIN main_inscls b ON a.inscl = b.inscl
WHERE a.REG_DATETIME BETWEEN '2018-08-01' AND '2018-08-31'
GROUP BY a.INSCL ORDER BY AMOUNT DESC 