SELECT a.SURGEON_ID,CONCAT(c.FNAME,'',TRIM(c.LNAME))AS Provider, COUNT(CASE WHEN SUBSTR(NICKNAME,1,3) ='ฝัง' THEN '1' END) AS 'ฝังเข็ม',
COUNT(CASE WHEN SUBSTR(NICKNAME,4,6) ='บริบาล' THEN '1' END) AS 'บริบาล', 
COUNT(case WHEN left(NICKNAME,6) = 'การนวด' THEN '2'END) AS 'การนวด',
COUNT(CASE WHEN SUBSTR(NICKNAME,4,2) = 'อบ' THEN '4' END) AS 'อบ', 
COUNT(CASE WHEN SUBSTR(NICKNAME,4,5) = 'ประคบ' THEN '5' END) AS 'ประคบ', 
COUNT(CASE WHEN SUBSTR(NICKNAME,4,8) = 'ส่งเสริม' THEN '5' END) AS 'ส่งเสริม', 
COUNT(CODE) AS Total 
FROM mb_opd_operations a
INNER JOIN staff b ON a.SURGEON_ID = b.STAFF_ID
LEFT JOIN population c ON b.CID = c.CID
WHERE a.REG_DATETIME > '2018-09-26' 
AND a.CGD_ID = 15
GROUP BY a.SURGEON_ID ORDER BY a.SURGEON_ID