SELECT  CONCAT(c.FNAME,'',trim(c.LNAME)) as PROVIDER,a.STAFF_ID,a.SURGEON_ID,a.CODE,a.NICKNAME, COUNT(a.CODE) as AMOUNT
FROM mb_opd_operations a
INNER JOIN staff b ON a.STAFF_ID = b.STAFF_ID
INNER JOIN population c ON b.CID = c.CID
WHERE a.REG_DATETIME > '2018-09-25'
AND a.NICKNAME BETWEEN 'PT00' AND 'PT75'
AND a.VISIT_ID NOT in (SELECT VISIT_ID FROM mobile_visits)
GROUP BY a.STAFF_ID ORDER BY AMOUNT DESC