SELECT DISTINCT '10953' AS HOSPCODE,b.HN AS PID,  a.visit_id  AS SEQ, b.REG_DATETIME AS DATETIME_SERV, a.datetime_ae AS DATETIME_AE,
AETYPE,AEPLACE,TYPEIN_AE,TRAFFIC,VEHICLE,ALCOHOL,'9' AS NACROTIC_DRUG,BELT,HELMET,
AIRWAY,STOPBLEED,SPLINT, FLUID, '6' as URGENCY, '' AS COMA_EYE, '' AS COMA_SPEAK, '' AS COMA_MOVEMENT,
DATE_FORMAT(NOW(), '%Y%m%d%H%i%s') AS D_UPDATE
FROM accidents a, opd_visits b
WHERE  b.REG_DATETIME BETWEEN '2017.01.01' AND '2017.09.30'
AND a.is_cancel = 0
AND a.VISIT_ID = b.VISIT_ID
