SELECT c.CID, c.HN ,a.ADM_ID AS AN,CONCAT(g.FNAME,'',TRIM(g.LNAME))AS FULLNAME, DATE_FORMAT(a.ADM_DT,'%Y-%m-%d')AS ADM_DATE ,
 a.DSC_DT AS DSC_DATE ,f.DEATH_DATE,
a.DSC_STATUS AS STATUS, a.DSC_TYPE AS TYPE,s.UNIT_NAME,i.ICD10_TM,f.CDEATH,f.CDEATH_A
FROM deaths f, opd_visits e
INNER JOIN ipd_reg a ON a.VISIT_ID = e.VISIT_ID AND a.IS_CANCEL = 0
INNER JOIN cid_hn c ON c.hn = e.hn 
INNER JOIN population g ON c.CID = g.CID 
INNER JOIN opd_diagnosis h ON e.VISIT_ID = h.VISIT_ID AND h.is_cancel=0 AND h.DXT_ID = 1
INNER JOIN icd10new i ON h.icd10 = i.icd10
INNER JOIN service_units s ON a.WARD_NO = s.UNIT_ID
WHERE a.DSC_DT > '2018.09.01'
AND a.DSC_STATUS > 7
AND a.VISIT_ID = e.VISIT_ID
AND e.HN = c.HN
AND f.CID = c.CID 
GROUP BY f.CID ORDER BY a.DSC_TYPE