SELECT c.CID, c.HN ,a.ADM_ID AS AN, DATE_FORMAT(a.ADM_DT,'%Y%m%d')AS ADM_DATE , DATE_FORMAT(a.DSC_DT,'%Y%m%d')AS DSC_DATE ,f.DEATH_DATE,
a.DSC_STATUS, a.DSC_TYPE,a.WARD_NO,f.CDEATH,f.CDEATH_A

FROM ipd_reg a,cid_hn c,opd_visits e,deaths f
WHERE a.DSC_DT >'20140101'
AND a.IS_CANCEL = 0
AND a.DSC_STATUS > 7
AND a.VISIT_ID = e.VISIT_ID
AND e.HN = c.HN
AND f.CID = c.CID 
GROUP BY f.CID