SELECT DISTINCT b.VISIT_ID, b.ADM_ID, b.ADM_DT , b.DSC_DT, a.DEATH_DATE, b.DSC_TYPE,DSC_STATUS
FROM deaths a, ipd_reg b,opd_visits c ,cid_hn e
WHERE b.ADM_DT BETWEEN '20151001' AND '20151231'
AND a.is_cancel = 0
AND b.IS_CANCEL = 0
AND a.CID = e.CID
AND b.VISIT_ID = c.VISIT_ID
#AND a.DEATH_DATE = b.DSC_DT
AND b.DSC_TYPE > 7 
GROUP BY b.ADM_ID 