SELECT 'รพ.ม่วงสามสิบ'as HOSPNAME,a.HN,CONCAT(trim(d.FNAME),' ',d.LNAME) AS FULLNAME,FLOOR(DATEDIFF(NOW(),d.BIRTHDATE)/365.25) as AGE, 
a.VISIT_ID , b.VISIT_ID, a.REG_DATETIME , b.REG_DATETIME, DATEDIFF(b.REG_DATETIME, a.REG_DATETIME) as DURATION, i.ICD10_TM
FROM opd_visits a
INNER JOIN opd_visits b ON a.HN = b.HN AND b.IS_CANCEL = 0
INNER JOIN cid_hn c ON a.HN = c.HN
INNER JOIN population d ON c.CID = d.CID
#RIGHT  JOIN f32 f ON  f.cid = d.CID
LEFT JOIN opd_diagnosis e ON a.VISIT_ID = e.VISIT_ID AND e.IS_CANCEL = 0
LEFT JOIN icd10new i ON e.ICD10 = i.ICD10 
WHERE a.REG_DATETIME BETWEEN '2018.04.30 00:00' AND '2018.11.01 23:59'
AND a.IS_CANCEL = 0
AND trim(a.HN) <> ' '
AND DATEDIFF(b.REG_DATETIME, a.REG_DATETIME) > 180
AND b.REG_DATETIME > a.REG_DATETIME
AND i.ICD10_TM BETWEEN 'F320' AND 'F339'
AND FLOOR(DATEDIFF(NOW(),d.BIRTHDATE)/365.25) >=60
GROUP BY a.HN


