SELECT '10953'AS HOSPCODE,'รพ.ม่วงสามสิบ 'AS HOSPNAME,k.VISIT_ID,k.HN,k.FULLNAME,k.AGE, k.SEX ,k.REG_DATETIME, k.UNIT_NAME,k.ICD_ALL, k.HOME_ADR, k.MOOBAN,k.TUMBON
FROM (
SELECT a.VISIT_ID, a.HN , CONCAT(trim(c.FNAME),'  ',c.LNAME) AS FULLNAME,
CASE 
WHEN c.SEX = 1 THEN 'ชาย'
WHEN c.SEX = 2 THEN 'หญิง'
END AS SEX,s.UNIT_NAME,FLOOR(DATEDIFF(NOW(),c.BIRTHDATE)/326.25) AS AGE, 
a.REG_DATETIME , c.TOWN_ID, c.HOME_ADR, t1.TOWN_NAME as 'MOOBAN', t2.TOWN_NAME as 'TUMBON',
GROUP_CONCAT(d.ICD10_TM) AS ICD_ALL
FROM opd_visits a
INNER JOIN cid_hn b ON a.hn = b.hn 
INNER JOIN population c ON b.cid = c.cid 
LEFT JOIN opd_diagnosis e ON a.visit_id = e.visit_id AND e.IS_CANCEL = 0
LEFT JOIN icd10new d ON e.ICD10 = d.ICD10 
LEFT JOIN service_units s ON a.unit_reg = s.unit_id
LEFT  JOIN appoints f ON (a.REG_DATETIME) = f.AP_DATE
INNER JOIN towns t1 ON c.TOWN_ID = t1.TOWN_ID
INNER JOIN towns t2 ON CONCAT(left(c.town_id,6),'00') = t2.town_id
WHERE a.REG_DATETIME BETWEEN '2018.10.01 00:00' AND '2019.12.30 23:59'
AND a.IS_CANCEL = 0
AND FLOOR(DATEDIFF(NOW(),c.BIRTHDATE)/326.25) >= 60
AND b.CID in (SELECT ff.cid FROM f32 ff)
GROUP BY  a.VISIT_ID
) AS k
WHERE  (FIND_IN_SET('F320',k.ICD_ALL) 
OR FIND_IN_SET('F321',k.ICD_ALL)
OR FIND_IN_SET('F322',k.ICD_ALL)
OR FIND_IN_SET('F323',k.ICD_ALL)
OR FIND_IN_SET('F324',k.ICD_ALL)
OR FIND_IN_SET('F325',k.ICD_ALL)
OR FIND_IN_SET('F326',k.ICD_ALL)
OR FIND_IN_SET('F327',k.ICD_ALL)
OR FIND_IN_SET('F328',k.ICD_ALL)
OR FIND_IN_SET('F329',k.ICD_ALL)
OR FIND_IN_SET('F330',k.ICD_ALL)
OR FIND_IN_SET('F331',k.ICD_ALL)
OR FIND_IN_SET('F332',k.ICD_ALL)
OR FIND_IN_SET('F333',k.ICD_ALL)
OR FIND_IN_SET('F334',k.ICD_ALL)
OR FIND_IN_SET('F335',k.ICD_ALL)
OR FIND_IN_SET('F336',k.ICD_ALL)
OR FIND_IN_SET('F337',k.ICD_ALL)
OR FIND_IN_SET('F338',k.ICD_ALL)
OR FIND_IN_SET('F339',k.ICD_ALL)
)
ORDER BY k.HN
