SELECT  c.IVS_DATE,a.IVT_ID,c.EXP_ID,b.IVT_NAME, a.QUANTITY, d.UUNIT_NAME, FORMAT(a.PACK_PRICE,2) AS PACK_PRICE
FROM order_details  a, inventory b, invoices c, ivt_units d
WHERE  c.IVS_DATE >= '2016.10.01' 
AND a.IVS_ID = c.IVS_ID AND a.IVT_ID  = b.IVT_ID 
#AND c.EXP_ID  BETWEEN '013' AND '025'
AND c.EXP_ID  =013

AND a.UUNIT_ID =d.UUNIT_ID
GROUP BY a.IVT_ID ORDER BY c.IVS_DATE  ;