SELECT DISTINCT a.REG_DATETIME , a.VISIT_ID, a.HN, c.`CODE`, c.TNAME, b.STAFF_ID ,  b.SURGEON_ID,
CASE
WHEN a.VISIT_ID NOT IN  (SELECT VISIT_ID FROM mobile_visits) THEN 1
WHEN a.VISIT_ID IN (SELECT VISIT_ID FROM mobile_visits )  THEN 2
END AS INOUTS, c.COST, c.ICD9_CODE
FROM  opd_visits a, opd_operations b, icd9cm c
WHERE a.REG_DATETIME BETWEEN '2017.03.01 00:00' AND '2017.03.01 23:59'
AND a.VISIT_ID = b.VISIT_ID
AND a.IS_CANCEL = 0
AND b.IS_CANCEL = 0
AND b.icd9 = c.ICD9
AND c.CGD_ID = '15'