SELECT a.VISIT_ID, a.HN ,a.REG_DATETIME, c.FNAME, c.LNAME ,c.SEX, c.BIRTHDATE, d.UNIT_ID, d.UNIT_NAME
FROM opd_visits a, cid_hn b, population c, service_units d
WHERE a.REG_DATETIME BETWEEN '20170101' AND '20170131'
AND a.IS_CANCEL = 0
AND a.HN = b.HN
AND b.CID = c.CID 
AND a.UNIT_REG = d.UNIT_ID
GROUP BY a.VISIT_ID ORDER BY a.VISIT_ID
