SELECT o.VISIT_ID AS visits, c.HN AS 'HN',DATE_FORMAT(o.REG_DATETIME,'%Y%m%d')AS REG_DATETIME, p.FNAME AS 'ชื่อ', p.LNAME AS 'นามสกุล',
CASE 
WHEN p.sex = '1' THEN 'ชาย'
WHEN p.sex = '2' THEN 'หญิง'
END AS SEX,FLOOR(DATEDIFF(NOW(),p.BIRTHDATE)/365.25)AS AGE,u.CU_NAME
FROM population p, cid_hn c, opd_visits o
INNER JOIN cost_units u ON o.UNIT_ID = u.UNIT_ID
WHERE c.CID = p.CID 
AND o.HN = c.HN
AND o.REG_DATETIME BETWEEN '20141001' AND '20141002'
GROUP BY o.VISIT_ID  ORDER BY o.VISIT_ID, o.REG_DATETIME;