SELECT DISTINCT a.REG_DATETIME,a.HN,a.FNAME, a.LNAME, a.SEX, a.AGE ,a.`CODE`,
a.HOME_ADR, c.TOWN_NAME AS 'MOOBAN', d.TOWN_NAME AS 'TUMBOL',e.TOWN_NAME AS 'AUMPUR',a.PROVIDER
FROM mb_oper_dent60 a, towns c ,towns d, towns e
WHERE a.REG_DATETIME BETWEEN '20151001' AND '20160930'
AND a.TOWN_ID = c.TOWN_ID
AND CONCAT(left(a.TOWN_ID,6),'00') = d.TOWN_ID
AND CONCAT(left(a.TOWN_ID,4),'0000') = e.TOWN_ID
GROUP BY a.HN ORDER BY a.REG_DATETIME , a.HN  ; 