SELECT 'รพ.ม่วงสามสิบ'as HOSPNAME,a.HN,CONCAT(trim(d.FNAME),' ',d.LNAME) AS FULLNAME,
TIMESTAMPDIFF(year,d.BIRTHDATE,a.REG_DATETIME) as AGE, 
a.VISIT_ID , a.REG_DATETIME , ap.AP_DATE ,i.ICD10_TM
FROM appoints ap
LEFT OUTER JOIN opd_visits a ON ap.HN AND a.IS_CANCEL = 0
LEFT JOIN cid_hn c ON a.HN = c.HN
LEFT  JOIN population d ON c.CID = d.CID
RIGHT  JOIN f32 f ON  f.cid = d.CID
LEFT JOIN opd_diagnosis e ON a.VISIT_ID = e.VISIT_ID AND e.IS_CANCEL = 0
LEFT JOIN icd10new i ON e.ICD10 = i.ICD10 
WHERE ap.AP_DATE BETWEEN '2018.11.01 ' AND '2019.12.31'
AND trim(a.HN) <> ' '
AND i.ICD10_TM BETWEEN 'F320' AND 'F339'
AND TIMESTAMPDIFF(year,d.BIRTHDATE,a.REG_DATETIME) >=60
LIMIT 20

-- SELECT * FROM appoints  LIMIT 10
