SELECT MONTH(a.REG_DATETIME) AS mm ,COUNT(c.DRUG_ID) AS amount
FROM opd_visits a, prescriptions b, drugs c
WHERE a.REG_DATETIME > '2018.01.01'
AND a.VISIT_ID = b.VISIT_ID
AND a.IS_CANCEL = 0
AND b.DRUG_ID = c.DRUG_ID
AND c.DRUG_ID IN (0262,0263,2280,0266,0261,2359)
AND a.VISIT_ID NOT IN (SELECT VISIT_ID FROM ipd_reg)
GROUP BY mm