SELECT  month(a.REG_DATETIME) AS month,
COUNT(CASE WHEN(c.DRUG_ID = '0262') THEN '1' END) AS 'ฟ้าทะลายโจร' ,
COUNT(CASE WHEN(c.DRUG_ID = '0263') THEN '2' END) AS 'ขมิ้นชัน',
COUNT(CASE WHEN(c.DRUG_ID = '2280') THEN '3' END) AS 'แก้ไอมะขาม',
COUNT(CASE WHEN(c.DRUG_ID = '0266') THEN '4' END) AS 'น้ำมันไพล',
COUNT(CASE WHEN(c.DRUG_ID = '0261') THEN '5' END) AS 'เพชรสังฆาต',
COUNT(CASE WHEN(c.DRUG_ID = '2359') THEN '6' END) AS 'ยาเขียวหอม',
COUNT(CASE WHEN(c.DRUG_ID IN (0262,0263,2280,0266,0261,2359) ) THEN '7' END) AS 'รวม'
FROM opd_visits a, prescriptions b, drugs c
WHERE a.REG_DATETIME BETWEEN '2018.04.01' AND '2018.05.30'
AND a.VISIT_ID = b.VISIT_ID
AND a.IS_CANCEL =0
AND b.DRUG_ID = c.DRUG_ID
AND a.VISIT_ID NOT IN (SELECT VISIT_ID FROM ipd_reg)
GROUP BY month(a.REG_DATETIME)

