
SELECT k.ICD_NAME, k.CODE , COUNT(k.CODE) AS Amount
FROM 
(SELECT a.VISIT_ID, a.HN, a.REG_DATETIME, d.CODE, d.ICD_NAME
FROM  opd_visits a,cid_hn b , opd_diagnosis c , icd10new d
WHERE a.REG_DATETIME BETWEEN '20161001' AND '20170930'
AND a.IS_CANCEL = 0
AND a.HN = b.HN
AND a.VISIT_ID = c.VISIT_ID
AND c.ICD10 = d.ICD10
AND d.ICD10_TM BETWEEN 'c00' AND 'd48'
GROUP BY a.HN   ) as k
GROUP BY k.ICD_NAME ORDER BY Amount  DESC  LIMIT 10;