
SELECT  ov.HN, i.ICD10_TM
FROM  opd_visits ov
LEFT JOIN opd_diagnosis dx  ON dx.VISIT_ID = ov.VISIT_ID
INNER  JOIN icd10new i ON  i.ICD10_ID = dx.ICD10_ID AND i.ICD10_TM = 'i10'
WHERE ov.REG_DATETIME BETWEEN '20140101' AND '20140131'
AND ov.IS_CANCEL = 0
AND ov.VISIT_ID = dx.VISIT_ID
AND ov.VISIT_ID NOT IN (SELECT VISIT_ID FROM ipd_reg)
