SELECT  ICD10_TM , ICD_NAME ,COUNT(VISIT_ID) AS AMOUNT
FROM  mb_referout_all_list
WHERE  RF_DT BETWEEN '2017-01-01' AND '2017-12-30'
AND HOSPID NOT IN (SELECT HOSP_ID FROM hospbank)
GROUP BY ICD10_TM ORDER BY AMOUNT DESC