SELECT DISTINCT a.VISIT_ID , b.HN ,g.ADM_ID AS AN, a.HOSP_ID AS 'HOSPID',f.HOSP_NAME, b.REG_DATETIME, g.ADM_DT , a.RF_DT, a.STAFF_ID,RF_TYPE,a.UNIT_ID, c.UNIT_NAME,e.ICD10_TM,e.ICD_NAME,d.DXT_ID, d.DXG_ID
FROM refers a,service_units c, opd_diagnosis d, icd10new e, hosp_nhso f ,opd_visits b
 LEFT JOIN  ipd_reg g ON b.VISIT_ID = g.VISIT_ID AND g.IS_CANCEL =0
WHERE a.RF_DT > '2018.01.01'
AND a.IS_CANCEL = 0
AND a.VISIT_ID = b.VISIT_ID
AND a.RF_TYPE = '2'
AND a.UNIT_ID = c.UNIT_ID
AND a.VISIT_ID = d.VISIT_ID
AND d.ICD10 = e.ICD10
AND a.HOSP_ID = f.HOSP_ID
GROUP BY a.VISIT_ID 
LIMIT 10