SELECT DISTINCT  a.STAFF_ID , c.FNAME , c.LNAME ,COUNT(a.STAFF_ID) AS amount
FROM  mb_thaimedoper a, staff b
INNER JOIN population c ON b.CID = c.CID
WHERE  a.REGDATE BETWEEN '2017-01-01' AND '2017-01-31'
AND a.STAFF_ID = b.STAFF_ID
GROUP BY a.STAFF_ID  ORDER BY amount DESC