
ALTER TABLE `person`
ADD COLUMN `TELEPHONE`  varchar(15) NULL AFTER `D_UPDATE`,
ADD COLUMN `MOBILE`  varchar(15) NULL AFTER `TELEPHONE`;

ALTER TABLE `address`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `death`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `chronic`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `card`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `disability`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `women`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;


ALTER TABLE `drugallergy`
ADD COLUMN `provider`  varchar(15) NULL AFTER `D_UPDATE`;

ALTER TABLE `drugallergy`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `functional`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `icf`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `service`
ADD COLUMN `hsub`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `service`
ADD COLUMN `cid`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `prenatal`
ADD COLUMN `provider`  varchar(15) NULL AFTER `D_UPDATE`;

ALTER TABLE `prenatal`
ADD COLUMN `cid`  varchar(13) NULL AFTER `D_UPDATE`;


ALTER TABLE `diagnosis_opd`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `drug_opd`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `procedure_opd`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `charge_opd`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `surveillance`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `accident`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `labfu`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `chronicfu`
ADD COLUMN `chronicfuplace`  varchar(13) NULL AFTER `D_UPDATE`;


ALTER TABLE `chronicfu`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;


ALTER TABLE `appointment`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `dental`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `rehabilitation`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `ncdscreen`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `fp`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `prenatal`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `anc`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `labor`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `labfu`
ADD COLUMN `labplace`  varchar(5) NULL AFTER `D_UPDATE`;
ALTER TABLE `labfu`
ADD COLUMN `cid`  varchar(5) NULL AFTER `labplace`;


ALTER TABLE `postnatal`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `newborn`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `newborncare`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `epi`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `nutrition`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `specialpp`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;

ALTER TABLE `community_service`
ADD COLUMN `CID`  varchar(13) NULL AFTER `D_UPDATE`;



